version: '3'
services:
  video-gallery-v2:
    container_name: video-gallery-v2
    platform: linux/amd64
    image: mysql
    restart: always
    ports:
      - '5435:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - video-gallery-v2-volume:/var/lib/mysql

volumes:
  video-gallery-v2-volume:
